import sys
import yaml
import shutil
import subprocess
import numpy as np
from pathlib import Path

# Packages for visualization
import matplotlib.pyplot as plt
from math import tan, radians, sqrt
from mpl_toolkits.mplot3d import Axes3D

# Packages for generating mesh
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
from stl import mesh

# Booleans for debugging
show_vertices = False

# Vertices visualization function
def plot_vertices_3d(side_vertices):
    x, y, z = side_vertices[:, 0], side_vertices[:, 1], side_vertices[:, 2]

    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    ax.scatter(x, y, z)

    # Add vertex index to each point
    for i in range(len(side_vertices)):
        ax.text(x[i], y[i], z[i], str(i))

    plt.show()

# Build a numpy-stl Mesh from a set of vertices/faces
def build_mesh(vertices, faces):
    m = mesh.Mesh(np.zeros(faces.shape[0], dtype=mesh.Mesh.dtype))

    for i, f in enumerate(faces):
        for j in range(3):
            m.vectors[i][j] = vertices[f[j], :]

    return m

# Mesh STL file generating function
def save_stl(side_vertices, side_faces, filename):
    build_mesh(side_vertices, side_faces).save(filename)

    # Overwrite STL file timestamp so that same inputs produces a byte-identical file
    with open(filename, 'r+b') as f:
        f.write('Generated by robogami_description/generate_robot_description.py'.ljust(80)[:80].encode('ascii'))

# Compute mesh inertial properties
def compute_mass_properties(vertices, faces, density):
    volume, cog, inertia = build_mesh(vertices, faces).get_mass_properties()
    return volume * density, cog, inertia * density

# Add point mass representing motors
def add_point_mass(mass, cog, inertia, extra_mass, extra_pos):
    cog = np.asarray(cog, dtype=float)
    extra_pos = np.asarray(extra_pos, dtype=float)
    total_mass = mass + extra_mass

    if total_mass == 0:
        return total_mass, np.zeros(3), inertia

    total_cog = (mass * cog + extra_mass * extra_pos) / total_mass

    def parallel_axis_shift(point_mass, point):
        d = point - total_cog
        return point_mass * (np.dot(d, d) * np.eye(3) - np.outer(d, d))

    total_inertia = inertia + parallel_axis_shift(mass, cog) + parallel_axis_shift(extra_mass, extra_pos)
    return total_mass, total_cog, total_inertia

# Check if a valid configuration file is passed as an argument
if len(sys.argv) != 2 or not Path(sys.argv[1]).is_file() or not sys.argv[1].endswith((".yaml", ".yml")):
    sys.exit(f"Input config file error! Please specify a valid YAML file as an argument. Usage: {sys.argv[0]} <config.yaml>")

# Open config file
config_file = sys.argv[1]
with open(config_file, "r") as f:
    data = yaml.safe_load(f)

# Robot/mesh name for this config, e.g. "robogami" (baseline) or
# "robogami_custom". Meshes are namespaced by it so that regenerating one
# config's URDF cannot silently overwrite the mesh files another config's
# already-generated URDF still refers to.
suffix = Path(config_file).stem.replace("robogami_config_", "", 1)
robot = "robogami" if suffix == "baseline" else f"robogami_{suffix}"

# Load variables
vars_to_import = ['hexagon_side', 'hexagon_thickness', 'leg_width', 'leg_length', 'leg_angle', 'leg_thickness', 'density', 'motor_mass']
missing = [v for v in vars_to_import if v not in data]
if missing:
    raise KeyError(f"Missing keys in YAML config file: {missing}")
base_a, base_t, side_a, side_H, side_ang, side_c, density_g_cm3, motor_mass_g = (data[v] for v in vars_to_import)
density = density_g_cm3 * 1000.0 # convert g/cm^3 to kg/m^3
motor_mass = motor_mass_g / 1000.0 # convert g to kg

# Compute auxiliary dimensions
side_h = (side_a / 2.0) * tan(radians(side_ang))
side_b = side_H - side_h
base_r = sqrt(3.0)/2.0 * base_a

# Assume motors attached at same place as leg links
leg_attachment_positions = [
    [-base_r, 0, 0],
    [base_a/4.0*sqrt(3), -3.0*base_a/4.0, 0],
    [base_a/4.0*sqrt(3), 3.0*base_a/4.0, 0],
]

# Define 12 3D vertices of a hexagonal base shape
base_vertices = np.array([\
    [base_r, -base_a/2.0, base_t/2.0], # 0
    [base_r, base_a/2.0, base_t/2.0], # 1
    [0, base_a, base_t/2.0], # 2
    [-base_r, base_a/2.0, base_t/2.0], # 3
    [-base_r, -base_a/2.0, base_t/2.0], # 4
    [0, -base_a, base_t/2.0], # 5
    [base_r, -base_a/2.0, -base_t/2.0], # 6
    [base_r, base_a/2.0, -base_t/2.0], # 7
    [0, base_a, -base_t/2.0], # 8
    [-base_r, base_a/2.0, -base_t/2.0], # 9
    [-base_r, -base_a/2.0, -base_t/2.0], # 10
    [0, -base_a, -base_t/2.0], # 11
    ])

# Define 20 triangular faces for the hexagonal base shape using indexes of the vertices
# Note, each triangle is defined using vertice indexes in a specific order to create a valid mesh
base_faces = np.array([[0,1,2], [0,2,3], [0,3,4], [0,4,5], [7,6,11], [7,11,10], [7,10,9], [7,9,8], [0,6,7], [0,7,1], [1,7,2], [7,8,2], [2,8,3], [8,9,3], [10,4,3], [10,3,9], [11,6,0], [11,0,5], [10,11,5], [10,5,4]])

# Define 10 3D vertices of a leg shape
side_vertices = np.array([\
    [0, -side_a/2.0, side_c/2.0], # 0
    [0, side_a/2.0, side_c/2.0], # 1
    [-side_b, side_a/2.0, side_c/2.0], # 2
    [-side_b, -side_a/2.0, side_c/2.0], # 3
    [0, -side_a/2.0, -side_c/2.0], # 4
    [0, side_a/2.0, -side_c/2.0], # 5
    [-side_b, side_a/2.0, -side_c/2.0], # 6
    [-side_b, -side_a/2.0, -side_c/2.0], # 7
    [-side_b-side_h, 0, side_c/2.0], # 8
    [-side_b-side_h, 0, -side_c/2.0]]) # 9

# Visualize the vertices
if show_vertices:
    plot_vertices_3d(base_vertices)
    plot_vertices_3d(side_vertices)

# Define 16 triangular faces for the leg shape mesh using indexes of the vertices
side_faces = np.array([[0,1,3], [1,2,3], [1,5,2], [5,6,2], [5,4,7], [5,7,6], [4,0,7], [3,7,0], [0,5,1], [0,4,5], [2,6,8], [6,9,8], [7,3,8], [7,8,9], [3,2,8], [6,7,9]])

# Generate the base and leg mesh files
base_mesh_name = f"{robot}_base"
leg_mesh_name = f"{robot}_leg"
save_stl(base_vertices, base_faces, f'../meshes/{base_mesh_name}.stl')
save_stl(side_vertices, side_faces, f'../meshes/{leg_mesh_name}.stl')

# Mass properties of the base/leg shapes
base_mass, base_cog, base_inertia = compute_mass_properties(base_vertices, base_faces, density)
leg_mass, leg_cog, leg_inertia = compute_mass_properties(side_vertices, side_faces, density)

# The base plate carries the 3 leg actuators
base_with_motors_mass, base_with_motors_cog, base_with_motors_inertia = base_mass, base_cog, base_inertia
for motor_pos in leg_attachment_positions:
    base_with_motors_mass, base_with_motors_cog, base_with_motors_inertia = add_point_mass(
        base_with_motors_mass, base_with_motors_cog, base_with_motors_inertia, motor_mass, motor_pos)

# Link materials genersting function (for visualization/debugging)
def generate_urdf_material_color(name, rgbs):
    r, g, b, a = rgbs

    return "\n".join([
        f'\t<material name="{name}">',
        f'\t\t<color rgba="{r} {g} {b} {a}"/>',
        '\t</material>\n'
    ])

# Link URDF string generating function
def generate_link_urdf_str(link_name, mesh_name, mass, cog, inertia, offset=0):
    cog_x, cog_y, cog_z = cog[0] + offset, cog[1], cog[2]
    ixx, ixy, ixz = inertia[0, 0], inertia[0, 1], inertia[0, 2]
    iyy, iyz = inertia[1, 1], inertia[1, 2]
    izz = inertia[2, 2]

    return "\n".join([
        '\t<link name="{}">'.format(link_name),
        '\t\t<inertial>',
        '\t\t\t<mass value="{}" />'.format(mass),
        '\t\t\t<origin rpy="0 0 0" xyz="{} {} {}"/>'.format(cog_x, cog_y, cog_z),
        '\t\t\t<inertia ixx="{}" ixy="{}" ixz="{}" iyy="{}" iyz="{}" izz="{}"/>'.format(ixx, ixy, ixz, iyy, iyz, izz),
        '\t\t</inertial>',
        '\t\t<visual>',
        '\t\t\t<origin rpy="0 0 0" xyz="{} 0 0"/>'.format(str(offset)),
        '\t\t\t<geometry>',
        '\t\t\t\t<mesh filename="package://robogami_description/meshes/{}.stl"/>'.format(mesh_name),
        '\t\t\t</geometry>',
        '\t\t\t<material name="Gray"/>',
        '\t\t</visual>',
        '\t</link>\n\n'
    ])
    
# Joint URDF string generating function
def generate_joint_urdf_str(joint_name, parent_link, child_link, ll, ul, axis, rpy, xyz):
    return "\n".join([
        '\t<joint name="{}" type="revolute">'.format(joint_name),
        '\t\t<parent link="{}"/>'.format(parent_link),
        '\t\t<child link="{}"/>'.format(child_link),
        '\t\t<axis xyz="{}"/>'.format(axis),
        '\t\t<limit effort="1" lower="{}" upper="{}" velocity="1"/>'.format(str(ll), str(ul)), # TODO double check joint limits
        '\t\t<origin rpy="{} {} {}" xyz="{} {} {}"/>'.format(*rpy, *xyz),
        '\t</joint>\n\n'
    ])

# Spherical joint URDF string generating function
def generate_spherical_joint_urdf_str(parent_link, child_link, extra_link1, extra_link2, extra_joint1, extra_joint2, extra_joint3):
    return "\n".join([
        '\t<link name="{}"/>\n'.format(extra_link1), # two virtual links
        '\t<link name="{}"/>\n'.format(extra_link2),
        '\t<joint name="{}" type="revolute">'.format(extra_joint1), # X rotation joint
        '\t\t<parent link="{}"/>'.format(parent_link),
        '\t\t<child link="{}"/>'.format(extra_link1),
        '\t\t<axis xyz="1 0 0"/>',
        '\t\t<limit effort="1" lower="-1.56" upper="1.56" velocity="1"/>',
        '\t\t<origin rpy="0 {} 0" xyz="{} 0 0"/>'.format(radians(180), -side_H),
        '\t</joint>\n',
        '\t<joint name="{}" type="revolute">'.format(extra_joint2), # Y rotation joint
        '\t\t<parent link="{}"/>'.format(extra_link1),
        '\t\t<child link="{}"/>'.format(extra_link2),
        '\t\t<axis xyz="0 1 0"/>',
        '\t\t<limit effort="1" lower="0.1" upper="3.13" velocity="1"/>',
        '\t\t<origin rpy="0 0 0" xyz="0 0 0"/>',
        '\t</joint>\n',
        '\t<joint name="{}" type="revolute">'.format(extra_joint3), # Z ?? rotation joint
        '\t\t<parent link="{}"/>'.format(extra_link2),
        '\t\t<child link="{}"/>'.format(child_link),
        '\t\t<axis xyz="1 0 0"/>',
        '\t\t<limit effort="1" lower="-1.56" upper="1.56" velocity="1"/>',
        '\t\t<origin rpy="0 0 0" xyz="0 0 0"/>',
        '\t</joint>\n\n'
    ])

# Corner collision links generating function
def generate_corner_collision_links(link_name, parent_link, joint_origin, material):
    return "\n".join([
        '\t<link name="{}">'.format(link_name),
        '\t\t<visual>',
        '\t\t\t<geometry>',
        '\t\t\t\t<sphere radius="0.001"/>',
        '\t\t\t</geometry>\n',
        '\t\t\t<material name="{}"/>'.format(material),
        '\t\t</visual>',
        '\t\t<collision>',
        '\t\t\t<geometry>',
        '\t\t\t\t<sphere radius="0.001"/>',
        '\t\t\t</geometry>',
        '\t\t</collision>',
        '\t</link>',
        '\n\t<joint name="{}" type="fixed">'.format(link_name+"_joint"),
        '\t\t<parent link="{}"/>'.format(parent_link),
        '\t\t<child link="{}"/>'.format(link_name),
        '\t\t<origin rpy="0 0 0" xyz="{} {} {}"/>'.format(*joint_origin),
        '\t</joint>\n\n'
    ])

def generate_fixed_joint_link(link_name, joint_name, parent_link, joint_origin):
    return "\n".join([
        '\t<link name="{}"/>\n'.format(link_name),
        '\t<joint name="{}" type="fixed">'.format(joint_name),
		'\t\t<parent link="{}"/>'.format(parent_link),
		'\t\t<child link="{}"/>'.format(link_name),
		'\t\t<origin rpy="{} {} {}" xyz="{} {} {}"/>'.format(*joint_origin),
	    '\t</joint>\n\n'
    ])

# Contact surface string generating function
def generate_contact_surface(parent_link, surface):
    return "\n".join([
        '\t<planar_surface name="{}" link="{}">'.format(surface, parent_link),
        '\t\t<origin xyz="0 0 0 " rpy="0 0 0" />',
        '\t\t<points>',
        '\t\t\t<point xy="0 0" />',
        '\t\t</points>',
        '\t\t<material name="plastic" />',
        '\t</planar_surface>\n\n',
    ])

# Write the URDF file (define links and joints)
urdf = open("../urdf/"+robot+".urdf", "w")

# URDF general info
config_lines = "\n".join("\t{}={}".format(k, v) for k, v in data.items())
urdf.write('<?xml version="1.0" ?>\n')
urdf.write('<!-- Generated from config file: {}\n{}\n-->\n'.format(config_file, config_lines))
urdf.write('<robot name="Robogami" xmlns:xacro="http://www.ros.org/wiki/xacro">\n')

# Materials
urdf.write('\n\t<!-- Materials -->\n')
urdf.write(generate_urdf_material_color("Gray", (0.1, 0.1, 0.1, 0.7)))
urdf.write(generate_urdf_material_color("Red", (1, 0, 0, 1.0)))
urdf.write(generate_urdf_material_color("Green", (0, 1, 0, 1.0)))
urdf.write(generate_urdf_material_color("Blue", (0, 0, 1, 1.0)))

# Base hexagon link
urdf.write('\n\t<!-- Base hexagon link -->\n')
urdf.write(generate_link_urdf_str("base", base_mesh_name, base_with_motors_mass, base_with_motors_cog, base_with_motors_inertia))

# Legs lower links
urdf.write('\t<!-- Legs lower links -->\n')
urdf.write(generate_link_urdf_str("leg1", leg_mesh_name, leg_mass, leg_cog, leg_inertia))
urdf.write(generate_link_urdf_str("leg2", leg_mesh_name, leg_mass, leg_cog, leg_inertia))
urdf.write(generate_link_urdf_str("leg3", leg_mesh_name, leg_mass, leg_cog, leg_inertia))

# Joints connecting leg lower links to the hexagon base link (actuated DoFs)
urdf.write('\t<!-- Joints connecting leg lower links to the hexagon base link -->\n')
urdf.write(generate_joint_urdf_str("l1", "base", "leg1", 0, 1.4, "0 1 0", [0, 0, 0], leg_attachment_positions[0]))
urdf.write(generate_joint_urdf_str("l2", "base", "leg2", 0, 1.4, "0 1 0", [0, 0, radians(120.0)], leg_attachment_positions[1]))
urdf.write(generate_joint_urdf_str("l3", "base", "leg3", 0, 1.4, "0 1 0", [0, 0, radians(-120.0)], leg_attachment_positions[2]))

# Legs upper links
urdf.write('\t<!-- Legs upper links -->\n')
urdf.write(generate_link_urdf_str("leg1top", leg_mesh_name, leg_mass, leg_cog, leg_inertia, side_H))
urdf.write(generate_link_urdf_str("leg2top", leg_mesh_name, leg_mass, leg_cog, leg_inertia, side_H))
urdf.write(generate_link_urdf_str("leg3top", leg_mesh_name, leg_mass, leg_cog, leg_inertia, side_H))

# Spherical joints connecting leg lower and upper links (unactuated DoFs)
urdf.write('\t<!-- Spherical joints connecting leg lower and upper links -->\n')
urdf.write(generate_spherical_joint_urdf_str("leg1", "leg1top", "l1RotX", "l1RotY", "x_l1rotx", "x_l1roty", "x_l1top"))
urdf.write(generate_spherical_joint_urdf_str("leg2", "leg2top", "l2RotX", "l2RotY", "x_l2rotx", "x_l2roty", "x_l2top"))
urdf.write(generate_spherical_joint_urdf_str("leg3", "leg3top", "l3RotX", "l3RotY", "x_l3rotx", "x_l3roty", "x_l3top"))

# Top hexagon link
urdf.write('\t<!-- Top hexagon link -->\n')
urdf.write(generate_link_urdf_str("top", base_mesh_name, base_mass, base_cog, base_inertia, -base_r))

# Leg1 joint to top hexagon link
urdf.write('\t<!-- Leg1 joint to top hexagon link -->\n')
urdf.write(generate_joint_urdf_str("l1topBase", "leg1top", "top", 0, 1.56, "0 1 0", [0, radians(180.0), 0], [side_H, 0, 0]))

# Auxiliary virtual links and associalted joints for defining contact surfaces and closed chains
urdf.write('\t<!-- Auxiliary virtual links and associalted joints for defining contact surfaces and closed chains -->\n')
urdf.write('\t<link name="leg2TopMove"/>\n\n')
urdf.write('\t<link name="leg3TopMove"/>\n\n')
urdf.write(generate_joint_urdf_str("l2TopMove", "leg2top", "leg2TopMove", -1.56, 1.56, "0 1 0", [0, radians(-90.0), 0], [side_H, 0, 0]))
urdf.write(generate_joint_urdf_str("l3TopMove", "leg3top", "leg3TopMove", -1.56, 1.56, "0 1 0", [0, radians(-90.0), 0], [side_H, 0, 0]))
urdf.write(generate_fixed_joint_link("topCenter", "topCenter", "top", [0, radians(180.0), 0, -base_a*sqrt(3)/2.0, 0, 0]))
urdf.write(generate_fixed_joint_link("topleg2", "topleg2", "top", [0, radians(90.0), radians(-120.0), (base_a/4.0*sqrt(3)) - base_a*sqrt(3), -3.0*base_a/4.0, 0]))
urdf.write(generate_fixed_joint_link("topleg3", "topleg3", "top", [0, radians(90.0), radians(120.0), (base_a/4.0*sqrt(3)) - base_a*sqrt(3), 3.0*base_a/4.0, 0]))

# Corner collision links
urdf.write('\t<!-- Corner collision shapes -->\n')
urdf.write(generate_corner_collision_links("leg1lowerLeftConner", "leg1", [-side_b, -side_a/2.0, 0], "Red"))
urdf.write(generate_corner_collision_links("leg1lowerRightConner", "leg1", [-side_b, side_a/2.0, 0], "Red"))
urdf.write(generate_corner_collision_links("leg1topLeftConner", "leg1top", [side_h, -side_a/2.0, 0], "Red"))
urdf.write(generate_corner_collision_links("leg1topRightConner", "leg1top", [side_h, side_a/2.0, 0], "Red"))
urdf.write(generate_corner_collision_links("leg2lowerLeftConner", "leg2", [-side_b, -side_a/2.0, 0], "Green"))
urdf.write(generate_corner_collision_links("leg2lowerRightConner", "leg2", [-side_b, side_a/2.0, 0], "Green"))
urdf.write(generate_corner_collision_links("leg2topLeftConner", "leg2top", [side_h, -side_a/2.0, 0], "Green"))
urdf.write(generate_corner_collision_links("leg2topRightConner", "leg2top", [side_h, side_a/2.0, 0], "Green"))
urdf.write(generate_corner_collision_links("leg3lowerLeftConner", "leg3", [-side_b, -side_a/2.0, 0], "Blue"))
urdf.write(generate_corner_collision_links("leg3lowerRightConner", "leg3", [-side_b, side_a/2.0, 0], "Blue"))
urdf.write(generate_corner_collision_links("leg3topLeftConner", "leg3top", [side_h, -side_a/2.0, 0], "Blue"))
urdf.write(generate_corner_collision_links("leg3topRightConner", "leg3top", [side_h, side_a/2.0, 0], "Blue"))

# Done!
urdf.write('\n</robot>')
urdf.close()
print("New Robogami URDF file using dimensions from "+config_file+" successfully generated")

# RSDF file start
Path("../rsdf/{}".format(robot)).mkdir(parents=True, exist_ok=True)
rsdf = open("../rsdf/{}/{}.rsdf".format(robot, "base"), "w")
rsdf.write('<robot name="robogami">\n\n')

# Planar surfaces
rsdf.write(generate_contact_surface("base", "Base"))
rsdf.write(generate_contact_surface("topCenter", "Top"))
rsdf.write(generate_contact_surface("topleg2", "TopLeg2"))
rsdf.write(generate_contact_surface("topleg3", "TopLeg3"))
rsdf.write(generate_contact_surface("leg2TopMove", "Leg2"))
rsdf.write(generate_contact_surface("leg3TopMove", "Leg3"))

# RSDF file end
rsdf.write('</robot>')
rsdf.close()

# Collision shapes generation
## Generate cloud files
convex_folder = f"../convex/{robot}/"
Path(convex_folder).mkdir(parents=True, exist_ok=True)
base_cloud = "base.qc"
base_cloud_file = open(convex_folder+base_cloud, "w")
base_cloud_file.write("3\n") # 3D space
base_cloud_file.write("12\n") # 12 points
for p in base_vertices:
    base_cloud_file.write(f"{p[0]} {p[1]} {p[2]}\n")
base_cloud_file.close()

leg_cloud = "leg.qc"
leg_cloud_file = open(convex_folder+leg_cloud, "w")
leg_cloud_file.write("3\n") # 3D space
leg_cloud_file.write("10\n") # 10 points
for p in side_vertices:
    leg_cloud_file.write(f"{p[0]} {p[1]} {p[2]}\n")
leg_cloud_file.close()

# Generate convex collision hull files from the cloud files
subprocess.run(["qconvex", "TI", convex_folder+base_cloud, "TO", convex_folder+"base-ch.txt", "Qt", "o", "f",], check=True)

subprocess.run(["qconvex", "TI", convex_folder+leg_cloud, "TO", convex_folder+"leg1-ch.txt", "Qt", "o", "f",], check=True)

# Make files for every robot link
shutil.copy(f"../convex/{convex_folder}/base-ch.txt", f"../convex/{convex_folder}/top-ch.txt")
shutil.copy(f"../convex/{convex_folder}/leg1-ch.txt", f"../convex/{convex_folder}/leg2-ch.txt")
shutil.copy(f"../convex/{convex_folder}/leg1-ch.txt", f"../convex/{convex_folder}/leg3-ch.txt")
shutil.copy(f"../convex/{convex_folder}/leg1-ch.txt", f"../convex/{convex_folder}/leg1top-ch.txt")
shutil.copy(f"../convex/{convex_folder}/leg1-ch.txt", f"../convex/{convex_folder}/leg2top-ch.txt")
shutil.copy(f"../convex/{convex_folder}/leg1-ch.txt", f"../convex/{convex_folder}/leg3top-ch.txt")

# Remove the cloud files
file = Path(convex_folder+base_cloud)
if file.exists(): file.unlink()
file = Path(convex_folder+leg_cloud)
if file.exists(): file.unlink()